### ISSUE TITLE
Test svg width with worst case input

### ISSUE THREAD

**Issue by notionparallax** [admiralstrand/turk#13]
if the whole message is `w` then what width do we need?

i.e. 
wwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwww

adjust to fit, then update the svg and the printing page size

**Comment by admiralstrand** [comment]
I guess ape the screen, so 20 chars.

**Comment by notionparallax** [comment]
![image](https://cloud.githubusercontent.com/assets/1865196/25778924/372f9a3e-334f-11e7-9c6e-6059dc6108f3.png)
So here's an illustration of the problem. Assuming a 20 char width (and, to quote the youth, I CBF to change that), then we can adjust the size of the output to handle different inputs.

If it's all `W` then we need a very small font, but if it's all `l` then we can have a huge font.
If we assume some kind of middle ground, then the somewhere in between.

The other option is to find two fixed width fonts that we like.

Orrrr... just do nothing.
